#
# Basic settings.
#
url: http://ihongkong.cc
baseurl: 
title: 老孙家热干面
description: Make The Web Awesome
avatar: /assets/img/head.jpg

#
# Icons
#
icons:
  rss: true
  email: ssd3237649@163.com
  github: sunpeter
  codepen: sunpeter
  bitbucket:
  twitter: 
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: # e.g. UA-000000-01
disqus:

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 5

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: false
ogp:
  image_url: /assets/img/head.jpg
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Styles: "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "hard_wrap", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor
