# Site settings
title: 老孙家热干面
email: ssd3237649@gmail.com
description: "Make The Web Awesome"
baseurl: ""
url: "http://sunpeter.github.io"
paginate: 5
# Build settings
markdown: kramdown
permalink: pretty
